version: '3.8'
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 80:80
      - 443:443 # for future ssl traffic
